package provider

type DataSourceCatalogEntry struct {
	ID               string   `json:"id"`
	Name             string   `json:"name"`
	Categories       []string `json:"categories"`
	CostModel        string   `json:"costModel"`
	Availability     string   `json:"availability"`
	CredentialEnvVar string   `json:"credentialEnvVar,omitempty"`
	ReferenceURI     string   `json:"referenceUri"`
	UsageNote        string   `json:"usageNote"`
	DataQualityNote  string   `json:"dataQualityNote"`
}

func DataSourceCatalog() []DataSourceCatalogEntry {
	return []DataSourceCatalogEntry{
		{ID: "osm-overpass", Name: "OpenStreetMap via Overpass API", Categories: []string{"poi", "competition", "road_accessibility"}, CostModel: "free_no_key", Availability: "active", ReferenceURI: "https://wiki.openstreetmap.org/wiki/Overpass_API", UsageNote: "Public endpoint with Redis caching; intended for modest MVP usage.", DataQualityNote: "Road data is an accessibility proxy only, not traffic volume, speed, congestion, or AADT."},
		{ID: "osm-nominatim", Name: "OpenStreetMap Nominatim", Categories: []string{"geocoding"}, CostModel: "free_no_key", Availability: "active", ReferenceURI: "https://operations.osmfoundation.org/policies/nominatim/", UsageNote: "Manual search only, maximum one public request per second, with cached results.", DataQualityNote: "Matches are preliminary until the user confirms the coordinates."},
		{ID: "osm-map", Name: "OpenStreetMap map preview", Categories: []string{"map"}, CostModel: "free_no_key", Availability: "active", ReferenceURI: "https://www.openstreetmap.org/copyright", UsageNote: "Embedded map preview with visible OpenStreetMap attribution.", DataQualityNote: "The preview is contextual and is not cadastral or survey evidence."},
		{ID: "tomtom", Name: "TomTom APIs", Categories: []string{"map", "geocoding", "routes", "traffic"}, CostModel: "free_key", Availability: "requires_key", CredentialEnvVar: "TOMTOM_API_KEY", ReferenceURI: "https://docs.tomtom.com/pricing", UsageNote: "Free monthly allowance and no card required; integration is deferred until a project key is supplied.", DataQualityNote: "Traffic flow is speed/congestion data, not a verified vehicle count or AADT."},
		{ID: "gistda", Name: "GISTDA Disaster Open API", Categories: []string{"flood"}, CostModel: "free_key", Availability: "requires_key", CredentialEnvVar: "GISTDA_API_KEY", ReferenceURI: "https://disaster.gistda.or.th/services/open-api", UsageNote: "Open flood and repeated-flood layers; account/API key and quota confirmation are required.", DataQualityNote: "Dataset date, spatial coverage and methodology must be preserved per result."},
		{ID: "gistda-flood-risk", Name: "GISTDA Flood Risk Layer (ArcGIS REST)", Categories: []string{"flood"}, CostModel: "free_no_key", Availability: "active", ReferenceURI: gistdaFloodRiskReference, UsageNote: "Queries the published flood-risk polygon layer around the submitted site; results are cached for 24 hours.", DataQualityNote: "A mapped overlap is factual for this layer only. No overlap does not establish that a site has no flood risk."},
		{ID: "doh-aadt", Name: "Department of Highways AADT + road control sections", Categories: []string{"traffic"}, CostModel: "free_no_key", Availability: "active", ReferenceURI: dohAADTReference, UsageNote: "Matches the current official annual AADT CSV to the closest official road control-section geometry with the same road number and section code; results are cached for 24 hours.", DataQualityNote: "AADT is an annual average for a matched road control section, not a live traffic count at the site's entrance. An unmatched section returns no traffic value."},
		{ID: "erc-thailand-power-map", Name: "Thailand Power Map (ERC)", Categories: []string{"electrical"}, CostModel: "free_no_key", Availability: "active_reference", ReferenceURI: thailandPowerMapReference, UsageNote: "Official index linking EGAT, PEA and MEA transmission/distribution power maps.", DataQualityNote: "Power-map information is for preliminary planning and is not a confirmation of connection feasibility or remaining capacity for a plot."},
		{ID: "mea-power-map", Name: "MEA Power Map for electricity users", Categories: []string{"electrical"}, CostModel: "free_public_map", Availability: "active", ReferenceURI: meaPowerMapReference, UsageNote: "Point-in-polygon lookup against MEA's public station-area layer for the configured year and voltage.", DataQualityNote: "MEA explicitly states that values may change and do not confirm supply capability, construction, reinforcement or network-extension requirements."},
		{ID: "pea-public-grid-gis", Name: "PEA public GIS — high-voltage grid and station layers", Categories: []string{"electrical"}, CostModel: "free_no_key", Availability: "active", ReferenceURI: peaGridReference, UsageNote: "Queries published PEA high-voltage conductor and station layers around the submitted coordinates; results are cached for 24 hours.", DataQualityNote: "Published line or station geometry is preliminary evidence only. It does not confirm a pole at the plot, available capacity, connection feasibility, or three-phase supply."},
		{ID: "mea-map-api", Name: "MEA Map API", Categories: []string{"electrical", "gis"}, CostModel: "free_allowance_then_paid", Availability: "requires_account_and_key", CredentialEnvVar: "MEA_MAP_API_KEY", ReferenceURI: "https://mapapi.mea.or.th/v2/home", UsageNote: "Account and API key are required; the published service includes a free allowance and paid usage tiers.", DataQualityNote: "Electrical map features still do not prove available connection capacity for a specific customer project."},
		{ID: "open-charge-map", Name: "Open Charge Map", Categories: []string{"competition"}, CostModel: "free_key", Availability: "requires_key", CredentialEnvVar: "OPEN_CHARGE_MAP_API_KEY", ReferenceURI: "https://openchargemap.io/develop", UsageNote: "Open community charging-location API with provider attribution.", DataQualityNote: "Coverage and operating status may be incomplete; cross-check against other sources."},
		{ID: "gemini-advisory", Name: "Gemini AI advisory", Categories: []string{"explanation", "recommendation_wording"}, CostModel: "free_key", Availability: "requires_key", CredentialEnvVar: "GEMINI_API_KEY", ReferenceURI: "https://ai.google.dev/gemini-api/docs/structured-output", UsageNote: "Generates structured Thai or English explanation from an existing analysis result after the API server is configured. It receives no customer name, address, coordinates or sample-place list.", DataQualityNote: "Not a factual provider and never calculates, alters or approves scores, ROI, payback, traffic, demand or electrical capacity."},
		{ID: "suphanburi-ev-chargers", Name: "Suphan Buri Provincial Office EV charging points", Categories: []string{"competition"}, CostModel: "free_no_key", Availability: "active", ReferenceURI: suphanburiChargerReference, UsageNote: "Imports the published CSV, extracts coordinates from its Google Maps destination links and deduplicates repeated connector rows before radius filtering.", DataQualityNote: "Geographic coverage is Suphan Buri only; a listed record does not independently verify current operation or connector availability."},
		{ID: "saraburi-ev-chargers", Name: "Saraburi Provincial Energy Office stations API", Categories: []string{"competition"}, CostModel: "free_no_key", Availability: "active", ReferenceURI: saraburiChargerReference, UsageNote: "Imports EV-labelled records from the provincial public JSON API and preserves publisher update metadata.", DataQualityNote: "Geographic coverage is Saraburi only; source content may include newly entered or test-labelled records and is reported as published."},
		{ID: "worldpop", Name: "WorldPop Global 2 Population API", Categories: []string{"population"}, CostModel: "free_no_key", Availability: "active", ReferenceURI: "https://api.worldpop.org/v2/", UsageNote: "No-key API aggregation within a generated site-radius polygon; results are cached for 30 days.", DataQualityNote: "Modelled population is labelled estimated, with dataset year, source version, resolution and methodology."},
		{ID: "thai-open-data", Name: "Open Government Data of Thailand", Categories: []string{"population", "poi", "competition", "gis"}, CostModel: "free_no_key", Availability: "active_selected_imports", ReferenceURI: "https://data.go.th/", UsageNote: "Selected datasets are enabled only after checking licence, update date, schema and geographic coverage.", DataQualityNote: "Coverage varies by agency and dataset; local datasets are never presented as nationwide."},
		{ID: "google-maps", Name: "Google Maps Platform", Categories: []string{"map", "geocoding", "places", "routes"}, CostModel: "paid_billing", Availability: "deferred_paid", CredentialEnvVar: "VITE_GOOGLE_MAPS_BROWSER_API_KEY / GOOGLE_MAPS_SERVER_API_KEY", ReferenceURI: "https://developers.google.com/maps/billing-and-pricing/pricing", UsageNote: "Monthly free usage caps exist, but a billing account and payment method are required.", DataQualityNote: "Use only after user approval, restricted keys, quotas and cost monitoring are configured."},
		{ID: "utility-capacity", Name: "MEA / PEA utility confirmation", Categories: []string{"electrical"}, CostModel: "manual_or_contract", Availability: "unavailable", ReferenceURI: "https://www.mea.or.th/", UsageNote: "No generic public API has been approved for verified site capacity.", DataQualityNote: "Never claim verified grid capacity without an actual utility document or provider response."},
	}
}
