import { createContext, useContext, useMemo, useState, type PropsWithChildren } from 'react'

export type Language = 'th' | 'en'

const translations = {
  th: {
    'Dashboard': 'แดชบอร์ด', 'Sites': 'พื้นที่', 'Analyses': 'การวิเคราะห์', 'Data Sources': 'แหล่งข้อมูล', 'Settings': 'ตั้งค่า',
    'Primary navigation': 'เมนูหลัก', 'Loading page…': 'กำลังโหลดหน้า…', 'This module is prepared for a later MVP iteration.': 'โมดูลนี้เตรียมไว้สำหรับการพัฒนาใน MVP ระยะถัดไป',
    'Candidate site screening and evidence readiness': 'คัดกรองพื้นที่และตรวจสอบความพร้อมของหลักฐานข้อมูล', 'New Site': 'เพิ่มพื้นที่ใหม่', 'Work queue': 'รายการงาน',
    'Sites awaiting review or provider data': 'พื้นที่ที่รอตรวจสอบหรือรอข้อมูลจากผู้ให้บริการ', 'sites': 'พื้นที่', 'Loading candidate sites…': 'กำลังโหลดพื้นที่…',
    'No candidate sites yet': 'ยังไม่มีพื้นที่ที่อยู่ระหว่างพิจารณา', 'Create the first site to start an evidence-based assessment.': 'สร้างพื้นที่แรกเพื่อเริ่มการประเมินโดยอ้างอิงหลักฐาน',
    'Create site': 'สร้างพื้นที่', 'Site': 'พื้นที่', 'Location': 'ตำแหน่ง', 'Data readiness': 'ความพร้อมของข้อมูล', 'Assessment': 'การประเมิน', 'Updated': 'อัปเดตล่าสุด', 'Action': 'การดำเนินการ', 'Open': 'เปิดดู', 'Not available': 'ไม่มีข้อมูล',
    'Candidate map': 'แผนที่พื้นที่', 'Selected site: ': 'พื้นที่ที่เลือก: ', 'Data status guide': 'คู่มือสถานะข้อมูล', 'Every result is labelled by evidence quality. Labels are part of the result, not decoration.': 'ผลลัพธ์ทุกส่วนจะแสดงคุณภาพของหลักฐานอย่างชัดเจน สถานะเหล่านี้เป็นส่วนหนึ่งของผลลัพธ์ ไม่ใช่เพียงการตกแต่ง',
    'Verified data': 'ข้อมูลที่ตรวจสอบแล้ว', 'Estimated data': 'ข้อมูลประมาณการ', 'Preliminary assessment': 'การประเมินเบื้องต้น', 'Missing data': 'ไม่มีข้อมูล', 'Source checked and ready to use': 'ตรวจสอบแหล่งที่มาแล้วและพร้อมใช้งาน', 'Modelled or estimated': 'มาจากแบบจำลองหรือการประมาณการ', 'Requires further validation': 'ต้องตรวจสอบเพิ่มเติม', 'Not currently available': 'ยังไม่มีข้อมูลในขณะนี้',
    'Modelled data': 'ข้อมูลจากแบบจำลอง', 'Community data': 'ข้อมูลจากชุมชน', 'Customer supplied': 'ลูกค้าระบุ', 'Province level': 'ระดับจังหวัด', 'District level': 'ระดับอำเภอ', 'Subdistrict level': 'ระดับตำบล', 'Site radius': 'ภายในรัศมีพื้นที่', 'Published service area': 'เขตบริการที่เผยแพร่', 'Plot level': 'ระดับแปลงที่ดิน',
    'Record customer-supplied site details before verification.': 'บันทึกรายละเอียดพื้นที่จากลูกค้าก่อนการตรวจสอบ', 'Saved inputs are not yet verified.': 'ข้อมูลที่บันทึกยังไม่ได้รับการตรวจสอบ',
		'Edit Site': 'แก้ไขพื้นที่', 'Update the customer-supplied details for this site.': 'แก้ไขรายละเอียดพื้นที่ที่ลูกค้าระบุ', 'Save changes': 'บันทึกการแก้ไข',
		'Edit': 'แก้ไข', 'Delete': 'ลบ', 'Delete this site?': 'ลบพื้นที่นี้หรือไม่?', 'Deleting this site will also permanently remove its analysis results. This cannot be undone.': 'การลบพื้นที่นี้จะลบผลการวิเคราะห์ทั้งหมดอย่างถาวร และไม่สามารถกู้คืนได้', 'Delete site': 'ลบพื้นที่', 'Deleting…': 'กำลังลบ…', 'Unable to delete this site. Please try again.': 'ไม่สามารถลบพื้นที่ได้ กรุณาลองใหม่อีกครั้ง',
    'e.g. Bang Na Candidate': 'เช่น พื้นที่ตัวอย่างบางนา', 'Access, frontage, ownership, or other customer-supplied context…': 'ทางเข้า หน้ากว้าง กรรมสิทธิ์ หรือข้อมูลอื่นที่ลูกค้าระบุ…',
    'Site name *': 'ชื่อพื้นที่ *', 'Address': 'ที่อยู่', 'Latitude': 'ละติจูด', 'Longitude': 'ลองจิจูด', 'Google Maps URL': 'ลิงก์ Google Maps', 'Land details': 'รายละเอียดที่ดิน', 'Land size *': 'ขนาดพื้นที่ *', 'Land size unit *': 'หน่วยพื้นที่ *', 'Notes': 'หมายเหตุ', 'Supporting evidence': 'เอกสารหรือหลักฐานประกอบ', 'Choose documents or photos': 'เลือกเอกสารหรือรูปภาพ', 'Files are staged locally in this foundation release.': 'ไฟล์จะถูกพักไว้ในเครื่องสำหรับรุ่นพื้นฐานนี้', 'Site location preview': 'ตัวอย่างตำแหน่งพื้นที่', 'Approximate location from user-supplied coordinates.': 'ตำแหน่งโดยประมาณจากพิกัดที่ลูกค้าระบุ', 'Cancel': 'ยกเลิก', 'Save Site': 'บันทึกพื้นที่', 'Saving…': 'กำลังบันทึก…', 'Square metres': 'ตารางเมตร', 'Rai': 'ไร่', 'Ngan': 'งาน', 'Square wah': 'ตารางวา',
    'Site record': 'ข้อมูลพื้นที่', 'Input provenance': 'ที่มาของข้อมูลนำเข้า', 'Customer-supplied inputs have not been independently verified.': 'ข้อมูลจากลูกค้ายังไม่ได้รับการตรวจสอบโดยอิสระ', 'Source: User supplied': 'แหล่งที่มา: ผู้ใช้ระบุ', 'Status: Preliminary': 'สถานะ: เบื้องต้น', 'Verification: Not completed': 'การตรวจสอบ: ยังไม่เสร็จสิ้น', 'Map': 'แผนที่', 'Run Analysis': 'เริ่มวิเคราะห์', 'Running…': 'กำลังวิเคราะห์…',
    'Analysis result': 'ผลการวิเคราะห์', 'Analysis': 'การวิเคราะห์', 'Overall suitability': 'ความเหมาะสมโดยรวม', 'Evidence quality': 'คุณภาพหลักฐาน', 'No score': 'ยังไม่มีคะแนน', 'Metric': 'ตัวชี้วัด', 'Score': 'คะแนน', 'Status': 'สถานะ', 'Source': 'แหล่งที่มา', 'Assumptions': 'สมมติฐาน', 'View source details': 'ดูรายละเอียดแหล่งข้อมูล', 'Source details': 'รายละเอียดแหล่งข้อมูล', 'Re-run analysis': 'วิเคราะห์ใหม่', 'Financial outlook': 'มุมมองทางการเงิน', 'Initial investment': 'เงินลงทุนเริ่มต้น', 'Monthly revenue': 'รายได้ต่อเดือน', 'Monthly operating cost': 'ต้นทุนดำเนินงานต่อเดือน', 'Monthly profit': 'กำไรต่อเดือน', 'Annual profit': 'กำไรต่อปี', 'ROI': 'ROI', 'Payback': 'ระยะคืนทุน', 'Plan values come from the project owner.': 'ข้อมูลแพ็กเกจมาจากเจ้าของโครงการ', 'Plan': 'แพ็กเกจ', 'Deterministic estimate': 'ประมาณการจากสูตรตายตัว', 'Staff-only financial assumptions. Customers do not enter these values.': 'สมมติฐานทางการเงินสำหรับพนักงานเท่านั้น ลูกค้าไม่ต้องกรอกข้อมูลส่วนนี้', 'uses the selected value from the plan investment range': 'ใช้ค่าที่เลือกจากช่วงเงินลงทุนของแพ็กเกจ', 'Monthly revenue and operating cost are internal assumptions entered by staff; they are not generated by the system.': 'รายได้และต้นทุนดำเนินงานต่อเดือนเป็นสมมติฐานภายในที่พนักงานระบุ ระบบไม่ได้สร้างตัวเลขขึ้นเอง', 'ROI and payback are deterministic pre-tax calculations and are not an investment approval.': 'ROI และระยะคืนทุนคำนวณแบบตายตัวก่อนภาษี ไม่ใช่การอนุมัติให้ลงทุน', 'Calculate ROI and payback': 'คำนวณ ROI และระยะคืนทุน', 'Calculating…': 'กำลังคำนวณ…', 'Financial assumptions': 'สมมติฐานทางการเงิน', 'Financial estimates will be added after operating assumptions are approved.': 'จะเพิ่มการประมาณการทางการเงินหลังจากยืนยันสมมติฐานการดำเนินงานแล้ว', 'Utility capacity not verified': 'ยังไม่ได้ตรวจสอบความสามารถรองรับของระบบไฟฟ้า', 'Utility capacity has not been verified with MEA or PEA.': 'ยังไม่ได้ตรวจสอบความสามารถรองรับของระบบไฟฟ้ากับ MEA หรือ PEA',
    'Department of Highways — traffic counts': 'กรมทางหลวง — ข้อมูลปริมาณจราจร', 'Department of Land Transport — registered EVs': 'กรมการขนส่งทางบก — รถ EV จดทะเบียน', 'WorldPop — population model': 'WorldPop — แบบจำลองประชากร', 'OpenStreetMap — community map data': 'OpenStreetMap — ข้อมูลแผนที่จากชุมชน', 'OpenStreetMap + connected charging-station datasets': 'OpenStreetMap + ชุดข้อมูลสถานีชาร์จที่เชื่อมต่อ', 'GISTDA — flood-risk map': 'GISTDA — แผนที่ความเสี่ยงน้ำท่วม', 'MEA — preliminary electricity map': 'MEA — แผนที่ระบบไฟฟ้าเบื้องต้น', 'MEA / PEA — preliminary electricity map': 'MEA / PEA — แผนที่ระบบไฟฟ้าเบื้องต้น', 'PEA Power Map available for this area': 'มี PEA Power Map สำหรับพื้นที่นี้', 'Open the official PEA Power Map to review the preliminary area information; capacity and three-phase supply still require PEA confirmation.': 'เปิด PEA Power Map ทางการเพื่อดูข้อมูลพื้นที่เบื้องต้น โดยความสามารถรองรับและไฟฟ้า 3 เฟสยังต้องยืนยันกับ PEA', 'No source connected yet': 'ยังไม่ได้เชื่อมแหล่งข้อมูล', 'See details for the dataset and calculation method.': 'ดูรายละเอียดเพื่อดูชุดข้อมูลและวิธีคำนวณ',
    'No published PEA high-voltage line found within the search radius': 'ไม่พบแนวโครงข่ายไฟฟ้าแรงสูง PEA ที่เผยแพร่ภายในรัศมีค้นหา', 'Nearest published PEA high-voltage line': 'แนวโครงข่ายไฟฟ้าแรงสูง PEA ที่เผยแพร่ใกล้ที่สุด', 'Nearest PEA station': 'สถานีไฟฟ้า PEA ใกล้ที่สุด', 'Voltage code': 'รหัสระดับแรงดัน', 'Phase code': 'รหัสเฟส', 'Conductor size': 'ขนาดตัวนำ', 'Public PEA GIS evidence only — it does not confirm a pole at the plot, remaining capacity, or three-phase connection.': 'เป็นหลักฐานจากชั้นข้อมูลสาธารณะ PEA เท่านั้น ไม่ได้ยืนยันว่ามีเสาไฟหน้าแปลง กำลังไฟคงเหลือ หรือจุดเชื่อมต่อไฟ 3 เฟส',
    'Information source': 'ข้อมูลนี้มาจากไหน', 'This is the source used for this analysis result.': 'แหล่งข้อมูลที่ระบบใช้สร้างผลลัพธ์ในแถวนี้', 'What to know before using this information': 'สิ่งที่ต้องรู้ก่อนใช้ข้อมูลนี้', 'Technical source details': 'รายละเอียดเชิงเทคนิคของแหล่งข้อมูล', 'Open original source': 'เปิดแหล่งข้อมูลต้นฉบับ',
    'Read the official source link for provider-specific usage details.': 'ดูรายละเอียดวิธีใช้ข้อมูลของแหล่งนี้ได้จากลิงก์ต้นฉบับ', 'Check data date, coverage and assumptions in the analysis result before use.': 'ตรวจสอบปีข้อมูล ขอบเขตข้อมูล และสมมติฐานในผลวิเคราะห์ก่อนใช้งาน', 'Reference available': 'มีแหล่งอ้างอิงพร้อมใช้', 'Selected datasets active': 'เปิดใช้เฉพาะชุดข้อมูลที่ตรวจสอบแล้ว', 'Account and API key required': 'ต้องมีบัญชีและ API key', 'Free public map': 'แผนที่สาธารณะใช้ฟรี', 'Free allowance, then paid': 'มีโควตาฟรี แล้วคิดค่าใช้จ่ายตามการใช้งาน',
    'Site name is required': 'กรุณาระบุชื่อพื้นที่', 'Enter a valid URL': 'กรุณากรอกลิงก์ให้ถูกต้อง', 'Land size must be greater than zero': 'ขนาดพื้นที่ต้องมากกว่า 0', 'Provide an address or latitude and longitude.': 'กรุณาระบุที่อยู่ หรือ ละติจูดและลองจิจูด', 'Both coordinates are required.': 'ต้องระบุทั้งละติจูดและลองจิจูด', 'Latitude must be between -90 and 90.': 'ละติจูดต้องอยู่ระหว่าง -90 ถึง 90', 'Longitude must be between -180 and 180.': 'ลองจิจูดต้องอยู่ระหว่าง -180 ถึง 180',
    'sqm': 'ตารางเมตร', 'rai': 'ไร่', 'ngan': 'งาน', 'sqwah': 'ตารางวา', 'poi': 'สถานที่สำคัญ', 'competition': 'คู่แข่ง', 'road_accessibility': 'การเข้าถึงทางถนน', 'traffic': 'การจราจร', 'flood': 'น้ำท่วม', 'electrical': 'ระบบไฟฟ้า', 'gis': 'ข้อมูล GIS', 'geocoding': 'ค้นหาพิกัด', 'map': 'แผนที่', 'routes': 'เส้นทาง', 'explanation': 'คำอธิบาย', 'recommendation_wording': 'ข้อความคำแนะนำ', 'population': 'ประชากร',
    'OpenStreetMap via Overpass API': 'OpenStreetMap ผ่าน Overpass API', 'OpenStreetMap Nominatim': 'OpenStreetMap Nominatim', 'OpenStreetMap map preview': 'ตัวอย่างแผนที่ OpenStreetMap', 'TomTom APIs': 'บริการ TomTom API', 'GISTDA Disaster Open API': 'GISTDA Disaster Open API', 'GISTDA Flood Risk Layer (ArcGIS REST)': 'GISTDA — ชั้นข้อมูลความเสี่ยงน้ำท่วม', 'Department of Highways AADT + road control sections': 'กรมทางหลวง — AADT และตอนควบคุมทาง', 'Thailand Power Map (ERC)': 'Thailand Power Map — กกพ.', 'MEA Map API': 'MEA Map API', 'Open Charge Map': 'Open Charge Map', 'WorldPop Global 2 Population API': 'WorldPop Global 2 Population API', 'WorldPop Global 2 Population Data': 'WorldPop — ข้อมูลประมาณการประชากร', 'Open Government Data of Thailand': 'ศูนย์กลางข้อมูลเปิดภาครัฐ (data.go.th)', 'Google Maps Platform': 'Google Maps Platform', 'MEA / PEA utility confirmation': 'การยืนยันจาก MEA / PEA', 'DLT registered BEV by province': 'กรมการขนส่งทางบก — รถ BEV จดทะเบียนรายจังหวัด',
    'This is a provincial registered-BEV indicator, not EV demand measured at the submitted coordinates.': 'เป็นตัวชี้วัดรถ BEV จดทะเบียนระดับจังหวัด ไม่ใช่ความต้องการใช้ EV ที่วัดจากพิกัดพื้นที่นี้', 'This is an official provincial registered-BEV count, not EV demand measured at the submitted coordinates.': 'เป็นจำนวนรถ BEV จดทะเบียนจากข้อมูลทางการระดับจังหวัด ไม่ใช่ความต้องการใช้ EV ที่วัดจากพิกัดพื้นที่นี้', 'The province is resolved through OpenStreetMap Nominatim reverse geocoding and remains a preliminary geographic assignment.': 'ระบบระบุจังหวัดจากการค้นหาพิกัดย้อนกลับของ OpenStreetMap Nominatim จึงยังเป็นการระบุพื้นที่เบื้องต้น', 'The province is resolved through OpenStreetMap Nominatim reverse geocoding; staff should confirm the submitted coordinates when the site is close to a provincial boundary.': 'ระบบระบุจังหวัดจากการค้นหาพิกัดย้อนกลับของ OpenStreetMap Nominatim พนักงานควรตรวจพิกัดอีกครั้งหากพื้นที่อยู่ใกล้แนวเขตจังหวัด', 'Hybrid and plug-in hybrid fuel categories are excluded; this value is not a count of all electrified vehicles.': 'ไม่นับรถไฮบริดและปลั๊กอินไฮบริด ดังนั้นค่านี้ไม่ใช่จำนวนรถไฟฟ้าทุกประเภท', 'Provincial charging-station datasets on data.go.th are unevenly published and are not combined into a nationwide factual count in this MVP.': 'ชุดข้อมูลสถานีชาร์จจาก data.go.th เผยแพร่ไม่เท่ากันในแต่ละจังหวัด และ MVP นี้ยังไม่นำมารวมเป็นจำนวนทั่วประเทศ',
    'Fuel-classified registered vehicles as at 28 February 2569': 'ข้อมูลรถจดทะเบียนแยกตามเชื้อเพลิง ณ 28 กุมภาพันธ์ 2569', 'Counts only DLT rows whose fuel type is exactly ไฟฟ้า (electric) for the province resolved from submitted coordinates.': 'นับเฉพาะรายการของกรมการขนส่งทางบกที่ระบุเชื้อเพลิงเป็น “ไฟฟ้า” ในจังหวัดที่ระบบระบุจากพิกัดที่ส่งมา', 'official_open_data_with_preliminary_geocoding': 'ข้อมูลเปิดทางการ พร้อมการระบุพื้นที่เบื้องต้น', 'Spatial query counts published GISTDA flood-risk polygons that intersect the requested site radius.': 'ค้นหาจำนวนขอบเขตพื้นที่เสี่ยงน้ำท่วมของ GISTDA ที่ทับซ้อนกับรัศมีพื้นที่ที่เลือก',
    'Department of Highways AADT 2568 + road control sections': 'กรมทางหลวง — ข้อมูล AADT และตอนควบคุมทาง', 'AADT 2568; DOH road geometry published Dec 2022': 'ข้อมูล AADT ปี 2568; แนวถนนกรมทางหลวงเผยแพร่เดือน ธ.ค. 2565', 'Nearest official road geometry within the requested radius, matched exactly to the annual AADT dataset by road number and control section. Geometry reference: https://giportal.mot.go.th/portal/home/item.html?id=7dd9dca0bd7948de9351b29302cd4c2c': 'เลือกแนวถนนกรมทางหลวงที่อยู่ใกล้ที่สุดในรัศมีที่กำหนด แล้วจับคู่รหัสทางหลวงและตอนควบคุมกับข้อมูล AADT รายปีแบบตรงกัน', 'AADT is the Department of Highways annual average daily traffic measurement for the matched road control section, not a live count at the site entrance.': 'AADT คือปริมาณจราจรเฉลี่ยต่อวันรายปีของตอนควบคุมถนนที่จับคู่ได้ ไม่ใช่จำนวนรถแบบเรียลไทม์ที่หน้าพื้นที่', 'The current public road-geometry layer is described by its publisher as a December 2022 snapshot; its route/control-section identifiers must match the annual AADT release exactly.': 'ชั้นข้อมูลแนวถนนที่เผยแพร่เป็นข้อมูล ณ เดือน ธ.ค. 2565 จึงต้องจับคู่รหัสเส้นทางและตอนควบคุมให้ตรงกับชุด AADT รายปี', 'Only the closest exact road-number and control-section match within the requested radius is shown; unmatched roads produce no AADT value.': 'แสดงเฉพาะถนนที่จับคู่รหัสทางหลวงและตอนควบคุมได้ตรงที่สุดในรัศมีที่เลือก หากจับคู่ไม่ได้ ระบบจะไม่สร้างค่า AADT',
    'Map preview unavailable': 'ไม่สามารถแสดงตัวอย่างแผนที่ได้', 'Configure the Google Maps browser API key to enable the map. The application remains usable without it.': 'ตั้งค่า Google Maps Browser API key เพื่อเปิดใช้งานแผนที่ ระบบยังใช้งานส่วนอื่นได้แม้ไม่มีคีย์', 'Save valid coordinates to preview this location.': 'บันทึกพิกัดที่ถูกต้องเพื่อดูตัวอย่างตำแหน่งนี้', 'km radius': 'รัศมี กม.', 'Loading analysis…': 'กำลังโหลดผลการวิเคราะห์…', 'Loading site…': 'กำลังโหลดข้อมูลพื้นที่…', 'Analysis not found.': 'ไม่พบผลการวิเคราะห์', 'Site not found.': 'ไม่พบพื้นที่'
    ,'Observed count only — not a suitability score.': 'เป็นจำนวนที่ตรวจพบเท่านั้น ไม่ใช่คะแนนความเหมาะสม', 'Observed result': 'ผลที่ตรวจพบ', 'mapped charging stations': 'สถานีชาร์จที่บันทึกในแผนที่', 'points of interest': 'สถานที่สำคัญ', 'POI sample': 'ตัวอย่างสถานที่ที่พบ', 'Stored examples only (up to 100 records). The total observed count includes every returned record.': 'เป็นตัวอย่างที่บันทึกไว้เท่านั้น (สูงสุด 100 รายการ) ส่วนจำนวนที่ตรวจพบรวมครอบคลุมทุกรายการที่ API ส่งกลับมา', 'Sample categories': 'หมวดหมู่จากตัวอย่าง', 'Example places': 'ตัวอย่างสถานที่'
    ,'Search an address or enter valid coordinates to preview this location.': 'ค้นหาที่อยู่หรือกรอกพิกัดที่ถูกต้องเพื่อดูตำแหน่งนี้', 'OpenStreetMap location preview': 'ตัวอย่างตำแหน่งจาก OpenStreetMap', 'Free map preview; not cadastral evidence.': 'แผนที่ตัวอย่างฟรี ไม่ใช่หลักฐานแนวเขตที่ดิน',
    'Enter a street address or place': 'กรอกที่อยู่หรือชื่อสถานที่', 'Provide an Address OR Latitude + Longitude.': 'ระบุที่อยู่ หรือ ละติจูดและลองจิจูด', 'Search free map data': 'ค้นหาจากแผนที่ฟรี', 'Searching…': 'กำลังค้นหา…', 'The address is sent to OpenStreetMap Nominatim only when you press search. Results are preliminary and must be confirmed.': 'ระบบจะส่งที่อยู่ไปยัง OpenStreetMap Nominatim เฉพาะเมื่อกดค้นหา ผลลัพธ์เป็นข้อมูลเบื้องต้นและต้องยืนยันอีกครั้ง', 'Address matches': 'ตำแหน่งที่พบ', 'Preliminary match': 'ผลการจับคู่เบื้องต้น', 'No address matches found.': 'ไม่พบตำแหน่งที่ตรงกับที่อยู่',
    'Paste a Google Maps link and the coordinates will be filled automatically.': 'วางลิงก์ Google Maps แล้วระบบจะเติมพิกัดให้อัตโนมัติ', 'Resolving Google Maps link…': 'กำลังอ่านลิงก์ Google Maps…', 'Coordinates filled. Please verify the map pin before continuing.': 'เติมพิกัดแล้ว กรุณาตรวจสอบหมุดบนแผนที่ก่อนดำเนินการต่อ',
    'Loading data sources…': 'กำลังโหลดแหล่งข้อมูล…', 'The MVP uses free and open providers first. Paid services remain disabled until the user explicitly approves billing.': 'MVP จะใช้แหล่งข้อมูลฟรีและข้อมูลเปิดก่อน บริการที่มีค่าใช้จ่ายจะยังไม่เปิดจนกว่าผู้ใช้จะอนุมัติ Billing อย่างชัดเจน', 'Free-first providers': 'แหล่งข้อมูลฟรีที่ใช้ก่อน', 'Active sources work now. Sources requiring a free key or dataset import are prepared but do not create factual results until configured.': 'แหล่งที่มีสถานะใช้งานทำงานได้แล้ว ส่วนแหล่งที่ต้องใช้คีย์ฟรีหรือนำเข้าชุดข้อมูลจะยังไม่สร้างผลข้อเท็จจริงจนกว่าจะตั้งค่า', 'Paid or manually verified sources': 'แหล่งข้อมูลที่มีค่าใช้จ่ายหรือต้องตรวจสอบด้วยเจ้าหน้าที่', 'These providers are documented separately and are not enabled. The application must notify the user before billing, a contract, or utility verification is required.': 'แหล่งเหล่านี้ถูกแยกไว้และยังไม่เปิดใช้งาน ระบบต้องแจ้งผู้ใช้ก่อนเมื่อจำเป็นต้องเปิด Billing ทำสัญญา หรือตรวจสอบกับการไฟฟ้า', 'Cost model': 'รูปแบบค่าใช้จ่าย', 'Usage': 'การใช้งาน', 'Data quality': 'คุณภาพข้อมูล', 'Official source': 'แหล่งข้อมูลทางการ', 'Free · no API key': 'ฟรี · ไม่ต้องใช้ API key', 'Free allowance · API key required': 'มีโควตาฟรี · ต้องใช้ API key', 'Free dataset download': 'ดาวน์โหลดชุดข้อมูลฟรี', 'Billing required': 'ต้องเปิด Billing', 'Manual verification or contract required': 'ต้องตรวจสอบด้วยเจ้าหน้าที่หรือทำสัญญา', 'Active now': 'ใช้งานได้แล้ว', 'Waiting for free key': 'รอคีย์ฟรี', 'Dataset import planned': 'วางแผนนำเข้าชุดข้อมูล', 'Disabled · paid': 'ปิดอยู่ · มีค่าใช้จ่าย', 'Manual verification required': 'ต้องตรวจสอบด้วยเจ้าหน้าที่',
    'Run new analysis': 'วิเคราะห์ใหม่', 'Assessment unavailable': 'ยังประเมินไม่ได้', 'Overall location score': 'คะแนนทำเลโดยรวม', 'Overall location screening score': 'คะแนนคัดกรองทำเลโดยรวม', 'Screening result': 'ผลการคัดกรอง', 'For preliminary screening only': 'ใช้คัดกรองเบื้องต้นเท่านั้น', 'Weighted data coverage': 'ความครอบคลุมข้อมูลตามน้ำหนัก', 'metrics included': 'ตัวชี้วัดที่นำมาคำนวณ', 'minimum': 'ขั้นต่ำ', 'Excluded from score': 'ไม่นำมาคิดคะแนน', 'Preliminary metric score': 'คะแนนตัวชี้วัดเบื้องต้น', 'Run a new analysis to calculate the preliminary score.': 'กดวิเคราะห์ใหม่เพื่อคำนวณคะแนนเบื้องต้น', 'Calculate preliminary score': 'คำนวณคะแนนคัดกรองเบื้องต้น', 'Calculating preliminary score…': 'กำลังคำนวณคะแนนคัดกรองเบื้องต้น…', 'A preliminary score requires at least 60% weighted data coverage.': 'ต้องมีข้อมูลครอบคลุมตามน้ำหนักอย่างน้อย 60% จึงจะคำนวณคะแนนเบื้องต้นได้', 'A score is calculated only when every required metric has an explicit approved value.': 'ระบบจะคำนวณคะแนนเมื่อทุกตัวชี้วัดที่จำเป็นมีค่าที่ชัดเจนและได้รับการรับรองแล้วเท่านั้น', 'This preliminary score must be reviewed with its sources and assumptions before an investment decision.': 'ต้องตรวจสอบคะแนนเบื้องต้นร่วมกับแหล่งข้อมูลและสมมติฐานก่อนตัดสินใจลงทุน', 'Location context': 'บริบทของทำเล', 'Analysis metrics': 'ตัวชี้วัดการวิเคราะห์', 'Select a row to review its source and assumptions.': 'เลือกแถวเพื่อดูแหล่งข้อมูลและสมมติฐาน โดยรายละเอียดจะแสดงเป็นหน้าต่างแยก', 'Result': 'ผลลัพธ์', 'Data status': 'สถานะข้อมูล', 'View details': 'ดูรายละเอียด', 'Evidence': 'หลักฐานข้อมูล', 'Close': 'ปิด',
    'Road accessibility proxy': 'ตัวชี้วัดการเข้าถึงทางถนน', 'Traffic volume': 'ปริมาณจราจร', 'Road access': 'ความสะดวกในการเข้า–ออก', 'EV demand': 'ความต้องการใช้รถ EV', 'Registered EVs': 'รถ EV จดทะเบียน', 'Registered EVs and provincial trend': 'รถ EV จดทะเบียนและแนวโน้มระดับจังหวัด', 'Population': 'ประชากร', 'Points of interest': 'สถานที่สำคัญ', 'Competition': 'คู่แข่ง', 'Flood risk': 'ความเสี่ยงน้ำท่วม', 'Electrical readiness': 'ความพร้อมระบบไฟฟ้า',
    'Source & assumptions': 'แหล่งข้อมูลและสมมติฐาน', 'No metric selected': 'ยังไม่ได้เลือกตัวชี้วัด', 'Dataset name': 'ชื่อชุดข้อมูล', 'Dataset version': 'รุ่นชุดข้อมูล', 'Observed date': 'วันที่ข้อมูล', 'Retrieved': 'วันที่ดึงข้อมูล', 'Data source': 'ประเภทแหล่งข้อมูล', 'Methodology': 'วิธีคำนวณ', 'Run status': 'สถานะการทำงาน', 'Key assumptions': 'สมมติฐานสำคัญ', 'completed': 'เสร็จสิ้น', 'open_data_api': 'API ข้อมูลเปิด', 'modelled_open_data_api': 'API ข้อมูลเปิดจากแบบจำลอง', 'unavailable': 'ไม่มีข้อมูล', 'Unavailable': 'ยังไม่มีแหล่งข้อมูล',
    'estimated people': 'คนโดยประมาณ', 'Modelled estimate — not an official census count.': 'ข้อมูลประมาณการจากแบบจำลอง ไม่ใช่จำนวนประชากรจากสำมะโนทางการ', 'vehicles/day (AADT)': 'คัน/วัน (AADT)', 'registered BEVs': 'รถ BEV จดทะเบียน', 'Provincial indicator — not EV demand at this exact location.': 'เป็นตัวชี้วัดระดับจังหวัด ไม่ใช่ความต้องการใช้ EV ณ จุดพื้นที่นี้', 'No comparable prior official DLT release is connected, so EV registration trend is not calculated.': 'ยังไม่ได้เชื่อมข้อมูล DLT ย้อนหลังที่เปรียบเทียบกันได้ จึงยังไม่คำนวณแนวโน้มรถ EV', 'Previous official count': 'จำนวนจากข้อมูลทางการครั้งก่อน', 'EV registrations started from zero in the comparison period.': 'ช่วงเปรียบเทียบเริ่มจากจำนวนรถเป็นศูนย์ จึงไม่แสดงเปอร์เซ็นต์', 'Compared with previous official count': 'เทียบกับข้อมูลทางการครั้งก่อน', 'increased': 'เพิ่มขึ้น', 'decreased': 'ลดลง', 'unchanged': 'คงเดิม', 'Highway': 'ทางหลวง', 'Control section': 'ตอนควบคุม', 'Matched official control section': 'จับคู่กับตอนควบคุมทางการแล้ว', 'm away': 'ม. จากแนวถนน', 'mapped major-road segments': 'ช่วงถนนสายหลักที่พบในแผนที่', 'm to nearest mapped major road': 'ม. จากถนนสายหลักที่พบใกล้ที่สุด', 'Road accessibility proxy — not a traffic count.': 'เป็นตัวชี้วัดการเข้าถึงทางถนน ไม่ใช่จำนวนรถ', 'Road-map assessment only — it does not confirm the actual entrance, turning movements, road width, or on-site obstructions.': 'ประเมินจากข้อมูลถนนบนแผนที่เท่านั้น ยังไม่ยืนยันทางเข้าจริง จุดกลับรถ ความกว้างถนน หรือสิ่งกีดขวางในพื้นที่', 'mapped flood-risk areas': 'พื้นที่เสี่ยงน้ำท่วมที่พบในชั้นข้อมูล', 'No mapped flood-risk area within the requested radius': 'ไม่พบพื้นที่เสี่ยงน้ำท่วมในชั้นข้อมูลภายในรัศมีที่เลือก', 'Published-layer overlap only — not a flood forecast or a no-risk conclusion.': 'เป็นผลการทับซ้อนกับชั้นข้อมูลที่เผยแพร่เท่านั้น ไม่ใช่การพยากรณ์น้ำท่วมหรือข้อสรุปว่าไม่มีความเสี่ยง', 'open_gis_api': 'API ข้อมูล GIS เปิด', 'official_open_data_and_gis': 'ข้อมูลเปิดและ GIS จากหน่วยงานทางการ',
    'Choose a franchise plan': 'เลือกแพ็กเกจแฟรนไชส์', 'Plan values come from the project owner. ROI remains unavailable until approved operating assumptions are supplied.': 'ข้อมูลแพ็กเกจมาจากเจ้าของโครงการ ระบบจะยังไม่แสดง ROI จนกว่าจะมีสมมติฐานการดำเนินงานที่ได้รับการยืนยัน', 'Loading franchise plans…': 'กำลังโหลดแพ็กเกจแฟรนไชส์…', 'Recommended area': 'พื้นที่แนะนำ', 'sq.wah': 'ตร.วา', 'EV charging stations': 'สถานีชาร์จ EV', 'Estimated investment': 'งบลงทุนโดยประมาณ', 'Starting franchise fee': 'ค่าแฟรนไชส์เริ่มต้น', 'Selected plan': 'แพ็กเกจที่เลือก', 'The supplied land area meets the plan recommendation.': 'พื้นที่ดินที่ระบุผ่านขนาดแนะนำของแพ็กเกจ', 'The supplied land area is below the plan recommendation.': 'พื้นที่ดินที่ระบุน้อยกว่าขนาดแนะนำของแพ็กเกจ', 'The source does not state whether the franchise fee is included in the investment range, so the system does not add them together.': 'แหล่งข้อมูลไม่ได้ระบุว่าค่าแฟรนไชส์รวมอยู่ในงบลงทุนแล้วหรือไม่ ระบบจึงไม่บวกยอดทั้งสองเข้าด้วยกัน', 'ROI and payback are not calculated because revenue, utilisation, electricity tariff, rent and operating costs are still missing.': 'ยังไม่คำนวณ ROI และระยะคืนทุน เพราะยังขาดข้อมูลรายได้ อัตราการใช้งาน ค่าไฟ ค่าเช่า และต้นทุนดำเนินงาน',
    'S – Smart Café': 'S – ร้านกาแฟขนาดเล็ก', 'M – Lifestyle Café': 'M – ร้านกาแฟไลฟ์สไตล์', 'L – Lifestyle Hub': 'L – ศูนย์รวมบริการไลฟ์สไตล์',
    'Recommendation': 'คำแนะนำ', 'Financial model': 'แบบจำลองทางการเงิน', 'ROI (pre-tax)': 'ROI (ก่อนภาษี)', 'Payback period': 'ระยะคืนทุน', 'months': 'เดือน', 'Requires explicit financial assumptions.': 'ต้องมีสมมติฐานทางการเงินที่ระบุไว้อย่างชัดเจน', 'A recommendation is unavailable until the required factual data is supplied or verified.': 'ยังไม่สามารถให้คำแนะนำได้จนกว่าจะมีข้อมูลข้อเท็จจริงที่จำเป็นหรือผ่านการตรวจสอบ', 'Preliminary screening score is available. Review data coverage, sources and assumptions before any investment decision.': 'คะแนนคัดกรองเบื้องต้นพร้อมใช้งาน โปรดตรวจสอบความครอบคลุม แหล่งข้อมูล และสมมติฐานก่อนตัดสินใจลงทุน', 'Results are preliminary and subject to change as factual data becomes available and assumptions are updated. Electrical utility capacity is not verified unless an actual MEA/PEA source is attached.': 'ผลลัพธ์เป็นข้อมูลเบื้องต้นและอาจเปลี่ยนแปลงเมื่อมีข้อมูลจริงหรือปรับสมมติฐาน ความสามารถรองรับของระบบไฟฟ้าจะไม่ถือว่าตรวจสอบแล้วจนกว่าจะมีหลักฐานจริงจาก MEA หรือ PEA',
    'WorldPop population cells aggregated by its API within a generated circular polygon around the site.': 'รวมค่าประชากรจากเซลล์ข้อมูล WorldPop ภายในรูปหลายเหลี่ยมวงกลมที่สร้างตามรัศมีรอบพื้นที่', 'WorldPop is a modelled population estimate, not an official census count for the site.': 'WorldPop เป็นค่าประมาณประชากรจากแบบจำลอง ไม่ใช่จำนวนสำมะโนทางการของพื้นที่', 'The query uses a 32-segment approximation of the requested radius.': 'ขอบเขตค้นหาใช้รูปหลายเหลี่ยม 32 ด้านเพื่อประมาณวงกลมตามรัศมีที่เลือก', 'Population is not converted into a suitability score in this MVP.': 'MVP นี้ยังไม่นำจำนวนประชากรไปแปลงเป็นคะแนนความเหมาะสม', 'This is a road accessibility proxy from mapped road classes, not a traffic count, speed, congestion, or AADT measurement.': 'เป็นตัวชี้วัดการเข้าถึงจากประเภทถนนในแผนที่ ไม่ใช่จำนวนรถ ความเร็ว ความหนาแน่น หรือค่า AADT', 'Nearest-road distance is approximated from the returned OpenStreetMap way geometry vertices.': 'ระยะถึงถนนใกล้ที่สุดเป็นค่าประมาณจากจุดเรขาคณิตของถนนที่ OpenStreetMap ส่งกลับ', 'OpenStreetMap road classification and coverage may be incomplete or differ from official Thai classifications.': 'ประเภทและความครอบคลุมของถนนใน OpenStreetMap อาจไม่ครบหรือแตกต่างจากการจัดประเภททางการของไทย', 'No normalized traffic score is produced in this MVP.': 'MVP นี้ยังไม่สร้างคะแนนจราจรแบบปรับมาตรฐาน', 'No factual provider has been configured for this metric.': 'ยังไม่ได้ตั้งค่าแหล่งข้อมูลข้อเท็จจริงสำหรับตัวชี้วัดนี้', 'This is a spatial overlap with GISTDA\'s published flood-risk layer, not a flood forecast, water-depth estimate, loss estimate, or suitability score.': 'เป็นผลการทับซ้อนเชิงพื้นที่กับชั้นข้อมูลความเสี่ยงน้ำท่วมของ GISTDA ไม่ใช่การพยากรณ์ ระดับน้ำ ความเสียหาย หรือคะแนนความเหมาะสม', 'No mapped flood-risk area within the requested radius does not prove that the site has no flood risk.': 'การไม่พบพื้นที่เสี่ยงน้ำท่วมในชั้นข้อมูลภายในรัศมี ไม่ได้ยืนยันว่าพื้นที่นั้นไม่มีความเสี่ยงน้ำท่วม', 'Layer coverage, update schedule and classification must be checked with GISTDA before an investment decision.': 'ต้องตรวจสอบขอบเขต ความถี่การอัปเดต และเกณฑ์การจัดประเภทของชั้นข้อมูลกับ GISTDA ก่อนตัดสินใจลงทุน', 'No normalized flood score is produced in this MVP.': 'MVP นี้ยังไม่สร้างคะแนนความเสี่ยงน้ำท่วมแบบปรับมาตรฐาน', 'GISTDA flood-risk layer was unavailable; no flood-risk conclusion was produced.': 'ชั้นข้อมูลความเสี่ยงน้ำท่วมของ GISTDA ไม่พร้อมใช้งาน จึงยังไม่สรุปความเสี่ยงน้ำท่วม', 'Valid coordinates are required to query the published GISTDA flood-risk layer.': 'ต้องมีพิกัดที่ถูกต้องเพื่อค้นหาชั้นข้อมูลความเสี่ยงน้ำท่วมของ GISTDA',
    'Count of currently returned OpenStreetMap elements within the requested radius, deduplicated by OSM type and ID.': 'นับรายการ OpenStreetMap ที่ API ส่งกลับภายในรัศมีที่กำหนด โดยตัดรายการซ้ำจากชนิดและรหัส OSM', 'Count mapped motorway, trunk, primary, secondary and tertiary ways within the radius and approximate the nearest distance from returned way geometry vertices.': 'นับถนนประเภท motorway, trunk, primary, secondary และ tertiary ภายในรัศมี และประมาณระยะใกล้ที่สุดจากจุดเรขาคณิตของถนนที่ API ส่งกลับ', 'Coverage depends on voluntary OpenStreetMap contributions and may be incomplete.': 'ความครอบคลุมขึ้นอยู่กับข้อมูลที่ชุมชนร่วมกันบันทึกใน OpenStreetMap และอาจไม่ครบถ้วน', 'This is a factual count of returned tagged elements, not a normalized suitability score.': 'เป็นจำนวนรายการที่มีแท็กซึ่ง API ส่งกลับ ไม่ใช่คะแนนความเหมาะสมแบบปรับมาตรฐาน', 'The response preserves at most 100 example places; count remains the full deduplicated total.': 'ระบบเก็บตัวอย่างสถานที่สูงสุด 100 รายการ แต่จำนวนรวมยังเป็นยอดทั้งหมดหลังตัดรายการซ้ำ', 'Only charging stations mapped in OpenStreetMap are included; unmapped operators may be missing.': 'รวมเฉพาะสถานีชาร์จที่บันทึกใน OpenStreetMap ผู้ให้บริการที่ยังไม่ถูกบันทึกอาจไม่ปรากฏ', 'Connector availability, power, pricing, and operational status are not verified by this query.': 'คำขอนี้ไม่ได้ตรวจสอบหัวชาร์จ กำลังไฟ ราคา หรือสถานะการเปิดให้บริการ', 'No competition score is produced until a deterministic scoring rule is approved.': 'ระบบจะยังไม่สร้างคะแนนคู่แข่งจนกว่าสูตรคะแนนแบบแน่นอนจะได้รับการอนุมัติ',
    'Preliminary MEA Power Map guideline — not verified remaining capacity for this plot.': 'ข้อมูลแนวทางเบื้องต้นจาก MEA Power Map ไม่ใช่กำลังไฟคงเหลือที่ยืนยันสำหรับพื้นที่นี้', 'Nearest MEA published-area reference only — not capacity for this plot.': 'อ้างอิงขอบเขตพื้นที่สถานี MEA ที่เผยแพร่และใกล้ที่สุดเท่านั้น ไม่ใช่กำลังไฟของพื้นที่นี้', 'nearest published area': 'ถึงขอบเขตพื้นที่ที่เผยแพร่ใกล้ที่สุด', 'm from the published boundary': 'ม. จากขอบเขตที่เผยแพร่', 'MEA Power Map for electricity users': 'MEA Power Map สำหรับผู้ใช้ไฟฟ้า', 'official_public_power_map': 'แผนที่ระบบไฟฟ้าสาธารณะจากหน่วยงานทางการ', 'Point-in-polygon lookup against the station-area layer published by MEA for the selected year and voltage.': 'ตรวจสอบพิกัดกับขอบเขตพื้นที่สถานีที่ MEA เผยแพร่ตามปีและระดับแรงดันที่เลือก', 'Nearest published MEA station-area boundary lookup; the site does not intersect that area. Distance is calculated from the submitted point to the published polygon boundary.': 'ค้นหาขอบเขตพื้นที่สถานี MEA ที่เผยแพร่และใกล้ที่สุด เนื่องจากพิกัดไม่ได้อยู่ในขอบเขตดังกล่าว โดยคำนวณระยะจากพิกัดถึงเส้นขอบพื้นที่', 'This is a preliminary planning indicator from the published MEA Power Map, not verified remaining grid capacity for the submitted plot.': 'เป็นตัวชี้วัดเพื่อวางแผนเบื้องต้นจาก MEA Power Map ไม่ใช่กำลังไฟคงเหลือที่ผ่านการยืนยันสำหรับพื้นที่นี้', 'MEA states that map values may change and do not confirm supply capability, connection feasibility, construction, reinforcement, or network-extension requirements.': 'MEA ระบุว่าค่าบนแผนที่อาจเปลี่ยนแปลง และไม่ได้ยืนยันความสามารถในการจ่ายไฟ ความเป็นไปได้ในการเชื่อมต่อ งานก่อสร้าง การเสริมระบบ หรือการขยายโครงข่าย', 'A formal MEA technical review and connection request are required before an investment decision.': 'ต้องให้ MEA ตรวจสอบทางเทคนิคและยื่นคำขอเชื่อมต่ออย่างเป็นทางการก่อนตัดสินใจลงทุน', 'The displayed capacity belongs to the nearest published MEA station area, not to the submitted plot. It must not be treated as the plot\'s available capacity.': 'ค่าความจุที่แสดงเป็นของขอบเขตพื้นที่สถานี MEA ที่เผยแพร่และใกล้ที่สุด ไม่ใช่ของพื้นที่ที่ส่งเข้ามา และห้ามตีความว่าเป็นกำลังไฟคงเหลือของพื้นที่นั้น', 'No electrical-readiness score is produced in this MVP.': 'MVP นี้ยังไม่สร้างคะแนนความพร้อมระบบไฟฟ้า',
    'charging-station records found': 'รายการสถานีชาร์จที่พบ', 'Deduplicated across connected sources — coverage is not nationwide.': 'ตัดรายการซ้ำระหว่างแหล่งข้อมูลที่เชื่อมแล้ว แต่ข้อมูลยังไม่ครอบคลุมทั่วประเทศ', 'Connected source coverage': 'ขอบเขตของแหล่งข้อมูลที่เชื่อมต่อ', 'records': 'รายการ', 'Example charging stations': 'ตัวอย่างสถานีชาร์จ', 'Unnamed charging station': 'สถานีชาร์จที่ไม่ระบุชื่อ',
    'Competitor coverage is not sufficient for this area': 'ข้อมูลคู่แข่งยังไม่ครอบคลุมพื้นที่นี้', 'No competitor score is produced until a connected source returns local evidence.': 'ระบบจะไม่ให้คะแนนคู่แข่งจนกว่าแหล่งข้อมูลที่เชื่อมต่อจะพบหลักฐานในพื้นที่นี้', 'The search completed, but the connected sources do not yet establish complete coverage for this area. This result is excluded from scoring.': 'ระบบค้นหาคู่แข่งเสร็จแล้ว แต่แหล่งข้อมูลที่เชื่อมต่อยังยืนยันความครอบคลุมของพื้นที่นี้ไม่ได้ จึงไม่นำผลไปคิดคะแนน',
    'Combined charging-station evidence': 'หลักฐานสถานีชาร์จจากหลายแหล่ง', 'Provincial government charging-station datasets': 'ชุดข้อมูลสถานีชาร์จจากหน่วยงานจังหวัด', 'Suphan Buri Provincial Office EV charging points': 'จุดชาร์จ EV จากสำนักงานจังหวัดสุพรรณบุรี', 'Saraburi Provincial Energy Office stations API': 'API สถานีบริการจากสำนักงานพลังงานจังหวัดสระบุรี', 'Gemini AI advisory': 'Gemini AI สำหรับอธิบายผลวิเคราะห์', 'multi_source_open_data': 'ข้อมูลเปิดจากหลายแหล่ง', 'official_open_data_multi_source': 'ข้อมูลเปิดทางการจากหลายแหล่ง',
    'Suphan Buri province only': 'ครอบคลุมเฉพาะจังหวัดสุพรรณบุรี', 'Saraburi province only': 'ครอบคลุมเฉพาะจังหวัดสระบุรี', 'OpenStreetMap mapped coverage within the requested radius': 'ข้อมูลที่บันทึกใน OpenStreetMap ภายในรัศมีที่กำหนด',
    'Combine OpenStreetMap and connected provincial charging-station records, then deduplicate records within 20 metres or matching normalized names within 150 metres.': 'รวมรายการสถานีชาร์จจาก OpenStreetMap และชุดข้อมูลจังหวัดที่เชื่อมต่อ แล้วตัดรายการซ้ำเมื่อพิกัดห่างกันไม่เกิน 20 เมตร หรือชื่อที่ปรับรูปแบบแล้วตรงกันและห่างกันไม่เกิน 150 เมตร',
    'The combined count is the deterministic union of connected sources after coordinate-and-name deduplication; source coverage remains unequal across Thailand.': 'จำนวนรวมคำนวณแบบแน่นอนจากแหล่งข้อมูลที่เชื่อมต่อหลังตัดรายการซ้ำด้วยพิกัดและชื่อ แต่ความครอบคลุมของข้อมูลยังไม่เท่ากันทั่วประเทศไทย', 'Zero returned records mean zero in the connected sources for this query, not verified absence of competitors.': 'ผลลัพธ์ศูนย์หมายถึงไม่พบรายการในแหล่งข้อมูลที่เชื่อมต่อสำหรับคำขอนี้ ไม่ใช่การยืนยันว่าไม่มีคู่แข่ง',
    'AI-assisted assessment': 'การวิเคราะห์ประกอบด้วย AI', 'Gemini explains deterministic analysis results; it does not calculate or change scores, ROI, or factual data.': 'Gemini อธิบายผลการวิเคราะห์ที่ระบบคำนวณไว้ แต่ไม่คำนวณหรือเปลี่ยนคะแนน ROI หรือข้อมูลข้อเท็จจริง', 'Generate AI assessment': 'สร้างบทวิเคราะห์ด้วย AI', 'Generating AI assessment…': 'กำลังสร้างบทวิเคราะห์ด้วย AI…', 'AI summary': 'สรุปโดย AI', 'AI recommendation': 'ข้อเสนอแนะโดย AI', 'Strengths': 'จุดแข็ง', 'Risks': 'ความเสี่ยง', 'Required checks': 'สิ่งที่ต้องตรวจเพิ่ม', 'Set GEMINI_API_KEY on the API server before generating an AI assessment.': 'ตั้งค่า GEMINI_API_KEY ที่ API server ก่อนสร้างบทวิเคราะห์ด้วย AI', 'The AI provider is temporarily unavailable or its quota was exceeded.': 'AI ใช้งานไม่ได้ชั่วคราว หรือเกินโควตาการใช้งาน', 'The AI provider returned an unusable assessment.': 'AI ส่งผลวิเคราะห์ที่ระบบนำไปใช้ต่อไม่ได้', 'AI-assisted preliminary score': 'คะแนนคัดกรองเบื้องต้นที่ AI ช่วยประเมิน', 'AI-assisted metric score': 'คะแนนตัวชี้วัดที่ AI ช่วยประเมิน', 'Gemini assessed the collected evidence; the system validated each score and calculated the weighted total.': 'Gemini ประเมินจากข้อมูลที่ระบบรวบรวม แล้วระบบตรวจสอบคะแนนและคำนวณคะแนนรวมตามน้ำหนักอีกชั้นหนึ่ง',
    'Coverage currently includes only the connected Suphan Buri and Saraburi provincial datasets; zero records do not prove that no charging station exists.': 'ข้อมูลจังหวัดที่เชื่อมต่อในขณะนี้ครอบคลุมเฉพาะสุพรรณบุรีและสระบุรี การพบศูนย์รายการไม่ได้พิสูจน์ว่าไม่มีสถานีชาร์จ', 'A source record confirms only that the publisher returned that record; current operation, connector availability, power and access were not independently verified.': 'รายการจากแหล่งข้อมูลยืนยันเพียงว่าผู้เผยแพร่ส่งรายการนั้นกลับมา ระบบยังไม่ได้ตรวจสอบสถานะเปิดให้บริการ หัวชาร์จ กำลังไฟ และการเข้าถึงโดยอิสระ', 'Repeated rows and cross-source records are deterministically deduplicated by coordinates and normalized station name.': 'ระบบตัดแถวซ้ำและรายการซ้ำข้ามแหล่งแบบแน่นอนจากพิกัดและชื่อสถานีที่ปรับรูปแบบแล้ว',
    'The provider supplies evidence only; deterministic preliminary-v1 scoring is applied separately by backend logic.': 'แหล่งข้อมูลส่งเฉพาะหลักฐาน ส่วนคะแนนเบื้องต้น preliminary-v1 คำนวณแยกด้วยสูตรตายตัวในระบบหลังบ้าน', 'This public planning value is excluded from scoring until utility-confirmed site capacity is available.': 'ข้อมูลแผนระบบไฟฟ้าสาธารณะนี้จะไม่นำมาคิดคะแนนจนกว่าจะมีกำลังไฟของพื้นที่ที่การไฟฟ้ายืนยัน',
    'Deterministic preliminary-v1 scoring rule: AADT screening rule: 20 points at zero, increasing linearly to 100 at 80,000 vehicles/day.': 'สูตรคะแนน preliminary-v1: ค่า AADT เริ่มที่ 20 คะแนนเมื่อเป็นศูนย์ และเพิ่มแบบเส้นตรงจนถึง 100 คะแนนที่ 80,000 คัน/วัน',
    'Deterministic preliminary-v1 scoring rule: Road-proxy fallback: 70% nearest-major-road proximity and 30% mapped major-road count; this is not traffic volume.': 'สูตรคะแนน preliminary-v1 กรณีไม่มี AADT: ระยะใกล้ถนนหลัก 70% และจำนวนถนนหลักในแผนที่ 30% ซึ่งไม่ใช่ปริมาณรถจริง',
    'Deterministic preliminary-v1 scoring rule: Road-accessibility rule: 70% nearest-major-road proximity and 30% mapped major-road count; this does not verify the actual entrance, turning movements, road width or on-site obstructions.': 'สูตรคะแนนคัดกรองรุ่นเบื้องต้น v1: ระยะใกล้ถนนหลัก 70% และจำนวนถนนหลักในแผนที่ 30% โดยไม่ได้ยืนยันทางเข้าจริง จุดกลับรถ ความกว้างถนน หรือสิ่งกีดขวางในพื้นที่',
    'Deterministic preliminary-v1 scoring rule: Provincial BEV screening rule: 20 points at zero, increasing linearly to 100 at 300,000 registered BEVs; not local demand.': 'สูตรคะแนน preliminary-v1: จำนวน BEV จดทะเบียนระดับจังหวัดเริ่มที่ 20 คะแนนเมื่อเป็นศูนย์ และเพิ่มถึง 100 คะแนนที่ 300,000 คัน ไม่ใช่อุปสงค์ ณ จุดที่ดิน',
    'Deterministic preliminary-v1 scoring rule: Population rule: modelled density increases linearly from 10 to 100 points at 6,000 people/km².': 'สูตรคะแนน preliminary-v1: ความหนาแน่นประชากรจากแบบจำลองเพิ่มแบบเส้นตรงจาก 10 ถึง 100 คะแนนที่ 6,000 คน/ตร.กม.',
    'Deterministic preliminary-v1 scoring rule: POI rule: mapped POI density increases linearly from 10 to 100 points at 8 POIs/km².': 'สูตรคะแนน preliminary-v1: ความหนาแน่นสถานที่สำคัญในแผนที่เพิ่มแบบเส้นตรงจาก 10 ถึง 100 คะแนนที่ 8 แห่ง/ตร.กม.',
    'Deterministic preliminary-v1 scoring rule: Competition rule: starts at 80 with no mapped competitors and subtracts 8 points per deduplicated station, with a 0–100 clamp.': 'สูตรคะแนน preliminary-v1: เริ่มที่ 80 เมื่อไม่พบคู่แข่งในแหล่งที่เชื่อม และลด 8 คะแนนต่อสถานีหลังตัดรายการซ้ำ โดยจำกัดคะแนน 0–100',
    'Deterministic preliminary-v1 scoring rule: Flood-layer rule: 80 when no published risk polygon overlaps the radius; this does not mean zero flood risk.': 'สูตรคะแนน preliminary-v1: ได้ 80 เมื่อไม่พบขอบเขตเสี่ยงน้ำท่วมจากชั้นข้อมูลที่ทับซ้อนในรัศมี แต่ไม่ได้หมายความว่าไม่มีความเสี่ยง',
    'Deterministic preliminary-v1 scoring rule: Flood-layer rule: 40 for one overlapping published risk polygon, minus 5 for each additional polygon.': 'สูตรคะแนน preliminary-v1: ได้ 40 เมื่อพบขอบเขตเสี่ยงน้ำท่วมหนึ่งพื้นที่ และลดอีก 5 คะแนนต่อพื้นที่ที่เพิ่มขึ้น',
    'Analysis in progress.': 'กำลังวิเคราะห์ข้อมูลพื้นที่',
    'Analysis failed while collecting provider data.': 'การวิเคราะห์ไม่สำเร็จระหว่างดึงข้อมูลจากแหล่งข้อมูล',
    'This score is a deterministic preliminary screening indicator, not an investment approval.': 'คะแนนนี้เป็นตัวชี้วัดคัดกรองเบื้องต้นจากสูตรตายตัว ไม่ใช่การอนุมัติให้ลงทุน',
    'Missing metrics are excluded and the available weights are renormalized; review coverage before comparing sites.': 'ตัวชี้วัดที่ไม่มีข้อมูลจะไม่ถูกนำมาคำนวณ และระบบจะปรับน้ำหนักของข้อมูลที่เหลือใหม่ โปรดตรวจสอบความครอบคลุมก่อนเปรียบเทียบพื้นที่',
    'Electrical capacity is excluded unless a utility-confirmed site value becomes available.': 'จะไม่นำความพร้อมระบบไฟฟ้ามาคิดคะแนนจนกว่าจะมีข้อมูลกำลังไฟของพื้นที่ที่การไฟฟ้ายืนยัน',
    'No nearby official road geometry could be matched to an AADT road number and control section; the system did not infer a traffic count.': 'ไม่พบแนวถนนทางการใกล้พื้นที่ที่จับคู่กับเลขทางหลวงและตอนควบคุมของ AADT ได้ ระบบจึงไม่สร้างค่าปริมาณจราจรขึ้นเอง',
    'WorldPop was unavailable or did not complete in time; no population value was produced.': 'WorldPop ไม่พร้อมใช้งานหรือประมวลผลไม่ทันเวลา จึงไม่มีค่าประชากรสำหรับผลวิเคราะห์นี้',
    'No MEA or PEA supply capability has been verified for the submitted plot.': 'ยังไม่มีการยืนยันความสามารถในการจ่ายไฟจาก MEA หรือ PEA สำหรับพื้นที่ที่ส่งเข้ามา',
    'The matching MEA polygon did not publish a numeric capacity value; no value was inferred.': 'ขอบเขตพื้นที่ MEA ที่ตรงกันไม่ได้เผยแพร่ค่าความจุเป็นตัวเลข ระบบจึงไม่สร้างค่าแทนขึ้นเอง',
    'error.REQUEST_FAILED': 'ไม่สามารถเชื่อมต่อระบบได้ กรุณาลองใหม่อีกครั้ง',
    'error.INVALID_GEOCODING_QUERY': 'คำค้นหาตำแหน่งไม่ถูกต้อง กรุณาระบุคำค้นหาอย่างน้อย 3 ตัวอักษร',
    'error.GEOCODING_UNAVAILABLE': 'บริการค้นหาพิกัดฟรีไม่พร้อมใช้งานชั่วคราว กรุณาลองใหม่อีกครั้ง',
    'error.INVALID_INPUT': 'ข้อมูลที่กรอกไม่ถูกต้อง กรุณาตรวจสอบและลองใหม่', 'error.INVALID_GOOGLE_MAPS_URL': 'ลิงก์ Google Maps ไม่ถูกต้อง กรุณาใช้ลิงก์ HTTPS ของ Google Maps', 'error.GOOGLE_MAPS_COORDINATES_NOT_FOUND': 'ไม่พบพิกัดในลิงก์ปลายทางของ Google Maps', 'error.GOOGLE_MAPS_UNAVAILABLE': 'ไม่สามารถอ่านลิงก์ Google Maps ได้ในขณะนี้ กรุณาลองใหม่อีกครั้ง',
    'error.INVALID_LOCATION': 'กรุณาระบุที่อยู่ หรือระบุทั้งละติจูดและลองจิจูดให้ถูกต้อง',
    'error.SITE_CREATE_FAILED': 'ไม่สามารถบันทึกพื้นที่ได้ กรุณาลองใหม่อีกครั้ง',
		'error.SITE_UPDATE_FAILED': 'ไม่สามารถแก้ไขข้อมูลพื้นที่ได้ กรุณาลองใหม่อีกครั้ง',
		'error.SITE_DELETE_FAILED': 'ไม่สามารถลบพื้นที่ได้ กรุณาลองใหม่อีกครั้ง',
    'error.SITE_LIST_FAILED': 'ไม่สามารถโหลดรายการพื้นที่ได้ กรุณาลองใหม่อีกครั้ง',
    'error.SITE_NOT_FOUND': 'ไม่พบพื้นที่ที่ต้องการ',
    'error.SITE_LOAD_FAILED': 'ไม่สามารถโหลดข้อมูลพื้นที่ได้ กรุณาลองใหม่อีกครั้ง',
    'error.INVALID_RADIUS': 'รัศมีต้องเป็น 1,000, 3,000 หรือ 5,000 เมตร',
    'error.ANALYSIS_FAILED': 'ไม่สามารถวิเคราะห์พื้นที่ได้ กรุณาลองใหม่อีกครั้ง',
    'error.ANALYSIS_NOT_FOUND': 'ไม่พบผลการวิเคราะห์',
    'error.ANALYSIS_LOAD_FAILED': 'ไม่สามารถโหลดผลการวิเคราะห์ได้ กรุณาลองใหม่อีกครั้ง',
    'error.SCORING_UPDATE_FAILED': 'ไม่สามารถคำนวณคะแนนคัดกรองเบื้องต้นได้',
    'error.INVALID_LANGUAGE': 'ภาษาที่ระบุไม่ถูกต้อง',
    'error.AI_NOT_CONFIGURED': 'ยังไม่ได้ตั้งค่าบริการ AI',
    'error.AI_UNAVAILABLE': 'บริการ AI ไม่พร้อมใช้งานชั่วคราว หรือเกินโควตา',
    'error.AI_INVALID_RESPONSE': 'บริการ AI ส่งผลลัพธ์ที่ระบบไม่สามารถใช้งานได้',
    'error.AI_ASSESSMENT_FAILED': 'ไม่สามารถสร้างบทวิเคราะห์ด้วย AI ได้',
    'error.INVALID_FINANCIAL_INPUT': 'ข้อมูลสำหรับคำนวณทางการเงินไม่ถูกต้อง',
    'error.FRANCHISE_PLAN_NOT_FOUND': 'ไม่พบแพ็กเกจแฟรนไชส์ที่เลือก',
    'error.INVALID_ID': 'รหัสข้อมูลไม่ถูกต้อง',
    'View analysis': 'ดูผลวิเคราะห์',
    'Review the key results and data status for this location.': 'ตรวจดูผลลัพธ์สำคัญและสถานะข้อมูลของพื้นที่นี้',
    'Load map 2026, 115 kV': 'แผนที่ระบบไฟฟ้าฝั่งผู้ใช้ไฟฟ้า ปี 2569 · 115 กิโลโวลต์',
    'people per sq. km': 'คนต่อตร.กม.', 'Population density within the selected radius': 'ความหนาแน่นประชากรภายในรัศมีที่เลือก', 'Community context': 'บริบทชุมชน', 'Residential buildings mapped': 'อาคารพักอาศัยที่พบในแผนที่', 'Community areas mapped': 'พื้นที่ชุมชนที่พบในแผนที่',
    'Satellite map preview': 'ตัวอย่างแผนที่ภาพดาวเทียม', 'Selected location': 'ตำแหน่งพื้นที่ที่เลือก', 'Satellite preview; not cadastral evidence.': 'ภาพดาวเทียมเพื่อประกอบการพิจารณา ไม่ใช่หลักฐานแนวเขตที่ดิน', 'Map preview': 'ตัวอย่างแผนที่', 'Interactive road map': 'แผนที่ถนนแบบโต้ตอบ ซูมและเลื่อนได้',
    'official_open_data': 'ข้อมูลเปิดจากหน่วยงานทางการ'
  },
} as const

type TranslationKey = keyof typeof translations.th
type I18nValue = { language: Language; setLanguage: (language: Language) => void; t: (key: string) => string }
const I18nContext = createContext<I18nValue | null>(null)

export function I18nProvider({ children }: PropsWithChildren) {
  const [language, setLanguageState] = useState<Language>(() => (localStorage.getItem('rbc-language') as Language) || 'th')
  const setLanguage = (next: Language) => { setLanguageState(next); localStorage.setItem('rbc-language', next) }
  const value = useMemo(() => ({
    language,
    setLanguage,
    t: (key: string) => {
      if (language !== 'th') return key
      const translated = key in translations.th ? translations.th[key as TranslationKey] : key
      return translated
        .replaceAll('คะแนนเบื้องต้น preliminary-v1', 'คะแนนคัดกรองรุ่นเบื้องต้น v1')
        .replaceAll('สูตรคะแนน preliminary-v1', 'สูตรคะแนนคัดกรองรุ่นเบื้องต้น v1')
    },
  }), [language])
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>
}

export function useI18n() {
  const value = useContext(I18nContext)
  if (!value) throw new Error('useI18n must be used within I18nProvider')
  return value
}

export function LanguageSwitcher() {
  const { language, setLanguage } = useI18n()
  return <div className="language-switcher" aria-label="Language"><button type="button" className={language === 'th' ? 'active' : ''} onClick={() => setLanguage('th')}>ไทย</button><button type="button" className={language === 'en' ? 'active' : ''} onClick={() => setLanguage('en')}>EN</button></div>
}
