import { createContext, useContext, useMemo, useState, type PropsWithChildren } from 'react'

export type Language = 'th' | 'en'

const translations = {
  th: {
    'Dashboard': 'แดชบอร์ด', 'Sites': 'พื้นที่', 'Analyses': 'การวิเคราะห์', 'Data Sources': 'แหล่งข้อมูล', 'Settings': 'ตั้งค่า',
    'Primary navigation': 'เมนูหลัก', 'Loading page…': 'กำลังโหลดหน้า…', 'This module is prepared for a later MVP iteration.': 'โมดูลนี้เตรียมไว้สำหรับการพัฒนาใน MVP ระยะถัดไป',
    'Candidate site screening and evidence readiness': 'คัดกรองพื้นที่และตรวจสอบความพร้อมของหลักฐานข้อมูล', 'New Site': 'เพิ่มพื้นที่ใหม่', 'Work queue': 'รายการงาน',
    'Sites awaiting review or provider data': 'พื้นที่ที่รอตรวจสอบหรือรอข้อมูลจากผู้ให้บริการ', 'sites': 'พื้นที่', 'Loading candidate sites…': 'กำลังโหลดพื้นที่…',
    'No candidate sites yet': 'ยังไม่มีพื้นที่ที่อยู่ระหว่างพิจารณา', 'Create the first site to start an evidence-based assessment.': 'สร้างพื้นที่แรกเพื่อเริ่มการประเมินโดยอ้างอิงหลักฐาน',
    'Create site': 'สร้างพื้นที่', 'Site': 'พื้นที่', 'Location': 'ตำแหน่ง', 'Data readiness': 'ความพร้อมของข้อมูล', 'Assessment': 'การประเมิน', 'Updated': 'อัปเดตล่าสุด', 'Action': 'การดำเนินการ', 'Open': 'เปิดดู', 'Not available': 'ไม่มีข้อมูล',
    'Candidate map': 'แผนที่พื้นที่', 'Selected site: ': 'พื้นที่ที่เลือก: ', 'Data status guide': 'คู่มือสถานะข้อมูล', 'Every result is labelled by evidence quality. Labels are part of the result, not decoration.': 'ผลลัพธ์ทุกส่วนจะแสดงคุณภาพของหลักฐานอย่างชัดเจน สถานะเหล่านี้เป็นส่วนหนึ่งของผลลัพธ์ ไม่ใช่เพียงการตกแต่ง',
    'Verified data': 'ข้อมูลที่ตรวจสอบแล้ว', 'Estimated data': 'ข้อมูลประมาณการ', 'Preliminary assessment': 'การประเมินเบื้องต้น', 'Missing data': 'ไม่มีข้อมูล', 'Source checked and ready to use': 'ตรวจสอบแหล่งที่มาแล้วและพร้อมใช้งาน', 'Modelled or estimated': 'มาจากแบบจำลองหรือการประมาณการ', 'Requires further validation': 'ต้องตรวจสอบเพิ่มเติม', 'Not currently available': 'ยังไม่มีข้อมูลในขณะนี้',
    'Record customer-supplied site details before verification.': 'บันทึกรายละเอียดพื้นที่จากลูกค้าก่อนการตรวจสอบ', 'Saved inputs are not yet verified.': 'ข้อมูลที่บันทึกยังไม่ได้รับการตรวจสอบ',
    'e.g. Bang Na Candidate': 'เช่น พื้นที่ตัวอย่างบางนา', 'Access, frontage, ownership, or other customer-supplied context…': 'ทางเข้า หน้ากว้าง กรรมสิทธิ์ หรือข้อมูลอื่นที่ลูกค้าระบุ…',
    'Site name *': 'ชื่อพื้นที่ *', 'Address': 'ที่อยู่', 'Latitude': 'ละติจูด', 'Longitude': 'ลองจิจูด', 'Google Maps URL': 'ลิงก์ Google Maps', 'Land details': 'รายละเอียดที่ดิน', 'Land size *': 'ขนาดพื้นที่ *', 'Land size unit *': 'หน่วยพื้นที่ *', 'Notes': 'หมายเหตุ', 'Supporting evidence': 'เอกสารหรือหลักฐานประกอบ', 'Choose documents or photos': 'เลือกเอกสารหรือรูปภาพ', 'Files are staged locally in this foundation release.': 'ไฟล์จะถูกพักไว้ในเครื่องสำหรับรุ่นพื้นฐานนี้', 'Site location preview': 'ตัวอย่างตำแหน่งพื้นที่', 'Approximate location from user-supplied coordinates.': 'ตำแหน่งโดยประมาณจากพิกัดที่ลูกค้าระบุ', 'Cancel': 'ยกเลิก', 'Save Site': 'บันทึกพื้นที่', 'Saving…': 'กำลังบันทึก…', 'Square metres': 'ตารางเมตร', 'Rai': 'ไร่', 'Ngan': 'งาน', 'Square wah': 'ตารางวา',
    'Site record': 'ข้อมูลพื้นที่', 'Input provenance': 'ที่มาของข้อมูลนำเข้า', 'Customer-supplied inputs have not been independently verified.': 'ข้อมูลจากลูกค้ายังไม่ได้รับการตรวจสอบโดยอิสระ', 'Source: User supplied': 'แหล่งที่มา: ผู้ใช้ระบุ', 'Status: Preliminary': 'สถานะ: เบื้องต้น', 'Verification: Not completed': 'การตรวจสอบ: ยังไม่เสร็จสิ้น', 'Map': 'แผนที่', 'Run Analysis': 'เริ่มวิเคราะห์', 'Running…': 'กำลังวิเคราะห์…',
    'Analysis result': 'ผลการวิเคราะห์', 'Analysis': 'การวิเคราะห์', 'Overall suitability': 'ความเหมาะสมโดยรวม', 'Evidence quality': 'คุณภาพหลักฐาน', 'No score': 'ยังไม่มีคะแนน', 'Metric': 'ตัวชี้วัด', 'Score': 'คะแนน', 'Status': 'สถานะ', 'Source': 'แหล่งที่มา', 'Assumptions': 'สมมติฐาน', 'View source details': 'ดูรายละเอียดแหล่งข้อมูล', 'Source details': 'รายละเอียดแหล่งข้อมูล', 'Re-run analysis': 'วิเคราะห์ใหม่', 'Financial outlook': 'มุมมองทางการเงิน', 'Initial investment': 'เงินลงทุนเริ่มต้น', 'Monthly revenue': 'รายได้ต่อเดือน', 'Monthly operating cost': 'ต้นทุนดำเนินงานต่อเดือน', 'Monthly profit': 'กำไรต่อเดือน', 'Annual profit': 'กำไรต่อปี', 'ROI': 'ROI', 'Payback': 'ระยะคืนทุน', 'Utility capacity not verified': 'ยังไม่ได้ตรวจสอบความสามารถรองรับของระบบไฟฟ้า', 'Utility capacity has not been verified with MEA or PEA.': 'ยังไม่ได้ตรวจสอบความสามารถรองรับของระบบไฟฟ้ากับ MEA หรือ PEA',
    'Map preview unavailable': 'ไม่สามารถแสดงตัวอย่างแผนที่ได้', 'Configure the Google Maps browser API key to enable the map. The application remains usable without it.': 'ตั้งค่า Google Maps Browser API key เพื่อเปิดใช้งานแผนที่ ระบบยังใช้งานส่วนอื่นได้แม้ไม่มีคีย์', 'Save valid coordinates to preview this location.': 'บันทึกพิกัดที่ถูกต้องเพื่อดูตัวอย่างตำแหน่งนี้', 'km radius': 'รัศมี กม.', 'Loading analysis…': 'กำลังโหลดผลการวิเคราะห์…', 'Loading site…': 'กำลังโหลดข้อมูลพื้นที่…', 'Analysis not found.': 'ไม่พบผลการวิเคราะห์', 'Site not found.': 'ไม่พบพื้นที่'
    ,'Observed count only — not a suitability score.': 'เป็นจำนวนที่ตรวจพบเท่านั้น ไม่ใช่คะแนนความเหมาะสม', 'Observed result': 'ผลที่ตรวจพบ', 'mapped charging stations': 'สถานีชาร์จที่บันทึกในแผนที่', 'points of interest': 'สถานที่สำคัญ', 'POI sample': 'ตัวอย่างสถานที่ที่พบ', 'Stored examples only (up to 100 records). The total observed count includes every returned record.': 'เป็นตัวอย่างที่บันทึกไว้เท่านั้น (สูงสุด 100 รายการ) ส่วนจำนวนที่ตรวจพบรวมครอบคลุมทุกรายการที่ API ส่งกลับมา', 'Sample categories': 'หมวดหมู่จากตัวอย่าง', 'Example places': 'ตัวอย่างสถานที่'
    ,'Search an address or enter valid coordinates to preview this location.': 'ค้นหาที่อยู่หรือกรอกพิกัดที่ถูกต้องเพื่อดูตำแหน่งนี้', 'OpenStreetMap location preview': 'ตัวอย่างตำแหน่งจาก OpenStreetMap', 'Free map preview; not cadastral evidence.': 'แผนที่ตัวอย่างฟรี ไม่ใช่หลักฐานแนวเขตที่ดิน',
    'Enter a street address or place': 'กรอกที่อยู่หรือชื่อสถานที่', 'Provide an Address OR Latitude + Longitude.': 'ระบุที่อยู่ หรือ ละติจูดและลองจิจูด', 'Search free map data': 'ค้นหาจากแผนที่ฟรี', 'Searching…': 'กำลังค้นหา…', 'The address is sent to OpenStreetMap Nominatim only when you press search. Results are preliminary and must be confirmed.': 'ระบบจะส่งที่อยู่ไปยัง OpenStreetMap Nominatim เฉพาะเมื่อกดค้นหา ผลลัพธ์เป็นข้อมูลเบื้องต้นและต้องยืนยันอีกครั้ง', 'Address matches': 'ตำแหน่งที่พบ', 'Preliminary match': 'ผลการจับคู่เบื้องต้น', 'No address matches found.': 'ไม่พบตำแหน่งที่ตรงกับที่อยู่',
    'Paste a Google Maps link and the coordinates will be filled automatically.': 'วางลิงก์ Google Maps แล้วระบบจะเติมพิกัดให้อัตโนมัติ',
    'Loading data sources…': 'กำลังโหลดแหล่งข้อมูล…', 'The MVP uses free and open providers first. Paid services remain disabled until the user explicitly approves billing.': 'MVP จะใช้แหล่งข้อมูลฟรีและข้อมูลเปิดก่อน บริการที่มีค่าใช้จ่ายจะยังไม่เปิดจนกว่าผู้ใช้จะอนุมัติ Billing อย่างชัดเจน', 'Free-first providers': 'แหล่งข้อมูลฟรีที่ใช้ก่อน', 'Active sources work now. Sources requiring a free key or dataset import are prepared but do not create factual results until configured.': 'แหล่งที่มีสถานะใช้งานทำงานได้แล้ว ส่วนแหล่งที่ต้องใช้คีย์ฟรีหรือนำเข้าชุดข้อมูลจะยังไม่สร้างผลข้อเท็จจริงจนกว่าจะตั้งค่า', 'Paid or manually verified sources': 'แหล่งข้อมูลที่มีค่าใช้จ่ายหรือต้องตรวจสอบด้วยเจ้าหน้าที่', 'These providers are documented separately and are not enabled. The application must notify the user before billing, a contract, or utility verification is required.': 'แหล่งเหล่านี้ถูกแยกไว้และยังไม่เปิดใช้งาน ระบบต้องแจ้งผู้ใช้ก่อนเมื่อจำเป็นต้องเปิด Billing ทำสัญญา หรือตรวจสอบกับการไฟฟ้า', 'Cost model': 'รูปแบบค่าใช้จ่าย', 'Usage': 'การใช้งาน', 'Data quality': 'คุณภาพข้อมูล', 'Official source': 'แหล่งข้อมูลทางการ', 'Free · no API key': 'ฟรี · ไม่ต้องใช้ API key', 'Free allowance · API key required': 'มีโควตาฟรี · ต้องใช้ API key', 'Free dataset download': 'ดาวน์โหลดชุดข้อมูลฟรี', 'Billing required': 'ต้องเปิด Billing', 'Manual verification or contract required': 'ต้องตรวจสอบด้วยเจ้าหน้าที่หรือทำสัญญา', 'Active now': 'ใช้งานได้แล้ว', 'Waiting for free key': 'รอคีย์ฟรี', 'Dataset import planned': 'วางแผนนำเข้าชุดข้อมูล', 'Disabled · paid': 'ปิดอยู่ · มีค่าใช้จ่าย', 'Manual verification required': 'ต้องตรวจสอบด้วยเจ้าหน้าที่',
    'Run new analysis': 'วิเคราะห์ใหม่', 'Assessment unavailable': 'ยังประเมินไม่ได้', 'Overall location score': 'คะแนนทำเลโดยรวม', 'A score is calculated only when every required metric has an explicit approved value.': 'ระบบจะคำนวณคะแนนเมื่อทุกตัวชี้วัดที่จำเป็นมีค่าที่ชัดเจนและได้รับการรับรองแล้วเท่านั้น', 'This preliminary score must be reviewed with its sources and assumptions before an investment decision.': 'ต้องตรวจสอบคะแนนเบื้องต้นร่วมกับแหล่งข้อมูลและสมมติฐานก่อนตัดสินใจลงทุน', 'Location context': 'บริบทของทำเล', 'Result': 'ผลลัพธ์', 'Data status': 'สถานะข้อมูล', 'View details': 'ดูรายละเอียด',
    'Road accessibility proxy': 'ตัวชี้วัดการเข้าถึงทางถนน', 'EV demand': 'ความต้องการใช้รถ EV', 'Population': 'ประชากร', 'Points of interest': 'สถานที่สำคัญ', 'Competition': 'คู่แข่ง', 'Flood risk': 'ความเสี่ยงน้ำท่วม', 'Electrical readiness': 'ความพร้อมระบบไฟฟ้า',
    'Source & assumptions': 'แหล่งข้อมูลและสมมติฐาน', 'No metric selected': 'ยังไม่ได้เลือกตัวชี้วัด', 'Dataset name': 'ชื่อชุดข้อมูล', 'Dataset version': 'รุ่นชุดข้อมูล', 'Observed date': 'วันที่ข้อมูล', 'Retrieved': 'วันที่ดึงข้อมูล', 'Data source': 'ประเภทแหล่งข้อมูล', 'Methodology': 'วิธีคำนวณ', 'Run status': 'สถานะการทำงาน', 'Key assumptions': 'สมมติฐานสำคัญ', 'completed': 'เสร็จสิ้น', 'open_data_api': 'API ข้อมูลเปิด', 'modelled_open_data_api': 'API ข้อมูลเปิดจากแบบจำลอง', 'unavailable': 'ไม่มีข้อมูล', 'Unavailable': 'ยังไม่มีแหล่งข้อมูล',
    'estimated people': 'คนโดยประมาณ', 'Modelled estimate — not an official census count.': 'ข้อมูลประมาณการจากแบบจำลอง ไม่ใช่จำนวนประชากรจากสำมะโนทางการ', 'mapped major-road segments': 'ช่วงถนนสายหลักที่พบในแผนที่', 'm to nearest mapped major road': 'ม. จากถนนสายหลักที่พบใกล้ที่สุด', 'Road accessibility proxy — not a traffic count.': 'เป็นตัวชี้วัดการเข้าถึงทางถนน ไม่ใช่จำนวนรถ',
    'Choose a franchise plan': 'เลือกแพ็กเกจแฟรนไชส์', 'Plan values come from the project owner. ROI remains unavailable until approved operating assumptions are supplied.': 'ข้อมูลแพ็กเกจมาจากเจ้าของโครงการ ระบบจะยังไม่แสดง ROI จนกว่าจะมีสมมติฐานการดำเนินงานที่ได้รับการยืนยัน', 'Loading franchise plans…': 'กำลังโหลดแพ็กเกจแฟรนไชส์…', 'Recommended area': 'พื้นที่แนะนำ', 'sq.wah': 'ตร.วา', 'EV charging stations': 'สถานีชาร์จ EV', 'Estimated investment': 'งบลงทุนโดยประมาณ', 'Starting franchise fee': 'ค่าแฟรนไชส์เริ่มต้น', 'Selected plan': 'แพ็กเกจที่เลือก', 'The supplied land area meets the plan recommendation.': 'พื้นที่ดินที่ระบุผ่านขนาดแนะนำของแพ็กเกจ', 'The supplied land area is below the plan recommendation.': 'พื้นที่ดินที่ระบุน้อยกว่าขนาดแนะนำของแพ็กเกจ', 'The source does not state whether the franchise fee is included in the investment range, so the system does not add them together.': 'แหล่งข้อมูลไม่ได้ระบุว่าค่าแฟรนไชส์รวมอยู่ในงบลงทุนแล้วหรือไม่ ระบบจึงไม่บวกยอดทั้งสองเข้าด้วยกัน', 'ROI and payback are not calculated because revenue, utilisation, electricity tariff, rent and operating costs are still missing.': 'ยังไม่คำนวณ ROI และระยะคืนทุน เพราะยังขาดข้อมูลรายได้ อัตราการใช้งาน ค่าไฟ ค่าเช่า และต้นทุนดำเนินงาน',
    'Recommendation': 'คำแนะนำ', 'Financial model': 'แบบจำลองทางการเงิน', 'ROI (pre-tax)': 'ROI (ก่อนภาษี)', 'Payback period': 'ระยะคืนทุน', 'months': 'เดือน', 'Requires explicit financial assumptions.': 'ต้องมีสมมติฐานทางการเงินที่ระบุไว้อย่างชัดเจน', 'A recommendation is unavailable until the required factual data is supplied or verified.': 'ยังไม่สามารถให้คำแนะนำได้จนกว่าจะมีข้อมูลข้อเท็จจริงที่จำเป็นหรือผ่านการตรวจสอบ', 'Results are preliminary and subject to change as factual data becomes available and assumptions are updated. Electrical utility capacity is not verified unless an actual MEA/PEA source is attached.': 'ผลลัพธ์เป็นข้อมูลเบื้องต้นและอาจเปลี่ยนแปลงเมื่อมีข้อมูลจริงหรือปรับสมมติฐาน ความสามารถรองรับของระบบไฟฟ้าจะไม่ถือว่าตรวจสอบแล้วจนกว่าจะมีหลักฐานจริงจาก MEA หรือ PEA',
    'WorldPop population cells aggregated by its API within a generated circular polygon around the site.': 'รวมค่าประชากรจากเซลล์ข้อมูล WorldPop ภายในรูปหลายเหลี่ยมวงกลมที่สร้างตามรัศมีรอบพื้นที่', 'WorldPop is a modelled population estimate, not an official census count for the site.': 'WorldPop เป็นค่าประมาณประชากรจากแบบจำลอง ไม่ใช่จำนวนสำมะโนทางการของพื้นที่', 'The query uses a 32-segment approximation of the requested radius.': 'ขอบเขตค้นหาใช้รูปหลายเหลี่ยม 32 ด้านเพื่อประมาณวงกลมตามรัศมีที่เลือก', 'Population is not converted into a suitability score in this MVP.': 'MVP นี้ยังไม่นำจำนวนประชากรไปแปลงเป็นคะแนนความเหมาะสม', 'This is a road accessibility proxy from mapped road classes, not a traffic count, speed, congestion, or AADT measurement.': 'เป็นตัวชี้วัดการเข้าถึงจากประเภทถนนในแผนที่ ไม่ใช่จำนวนรถ ความเร็ว ความหนาแน่น หรือค่า AADT', 'Nearest-road distance is approximated from the returned OpenStreetMap way geometry vertices.': 'ระยะถึงถนนใกล้ที่สุดเป็นค่าประมาณจากจุดเรขาคณิตของถนนที่ OpenStreetMap ส่งกลับ', 'OpenStreetMap road classification and coverage may be incomplete or differ from official Thai classifications.': 'ประเภทและความครอบคลุมของถนนใน OpenStreetMap อาจไม่ครบหรือแตกต่างจากการจัดประเภททางการของไทย', 'No normalized traffic score is produced in this MVP.': 'MVP นี้ยังไม่สร้างคะแนนจราจรแบบปรับมาตรฐาน', 'No factual provider has been configured for this metric.': 'ยังไม่ได้ตั้งค่าแหล่งข้อมูลข้อเท็จจริงสำหรับตัวชี้วัดนี้',
    'Count of currently returned OpenStreetMap elements within the requested radius, deduplicated by OSM type and ID.': 'นับรายการ OpenStreetMap ที่ API ส่งกลับภายในรัศมีที่กำหนด โดยตัดรายการซ้ำจากชนิดและรหัส OSM', 'Count mapped motorway, trunk, primary, secondary and tertiary ways within the radius and approximate the nearest distance from returned way geometry vertices.': 'นับถนนประเภท motorway, trunk, primary, secondary และ tertiary ภายในรัศมี และประมาณระยะใกล้ที่สุดจากจุดเรขาคณิตของถนนที่ API ส่งกลับ', 'Coverage depends on voluntary OpenStreetMap contributions and may be incomplete.': 'ความครอบคลุมขึ้นอยู่กับข้อมูลที่ชุมชนร่วมกันบันทึกใน OpenStreetMap และอาจไม่ครบถ้วน', 'This is a factual count of returned tagged elements, not a normalized suitability score.': 'เป็นจำนวนรายการที่มีแท็กซึ่ง API ส่งกลับ ไม่ใช่คะแนนความเหมาะสมแบบปรับมาตรฐาน', 'The response preserves at most 100 example places; count remains the full deduplicated total.': 'ระบบเก็บตัวอย่างสถานที่สูงสุด 100 รายการ แต่จำนวนรวมยังเป็นยอดทั้งหมดหลังตัดรายการซ้ำ', 'Only charging stations mapped in OpenStreetMap are included; unmapped operators may be missing.': 'รวมเฉพาะสถานีชาร์จที่บันทึกใน OpenStreetMap ผู้ให้บริการที่ยังไม่ถูกบันทึกอาจไม่ปรากฏ', 'Connector availability, power, pricing, and operational status are not verified by this query.': 'คำขอนี้ไม่ได้ตรวจสอบหัวชาร์จ กำลังไฟ ราคา หรือสถานะการเปิดให้บริการ', 'No competition score is produced until a deterministic scoring rule is approved.': 'ระบบจะยังไม่สร้างคะแนนคู่แข่งจนกว่าสูตรคะแนนแบบแน่นอนจะได้รับการอนุมัติ'
  },
} as const

type TranslationKey = keyof typeof translations.th
type I18nValue = { language: Language; setLanguage: (language: Language) => void; t: (key: string) => string }
const I18nContext = createContext<I18nValue | null>(null)

export function I18nProvider({ children }: PropsWithChildren) {
  const [language, setLanguageState] = useState<Language>(() => (localStorage.getItem('rbc-language') as Language) || 'th')
  const setLanguage = (next: Language) => { setLanguageState(next); localStorage.setItem('rbc-language', next) }
  const value = useMemo(() => ({ language, setLanguage, t: (key: string) => language === 'th' && key in translations.th ? translations.th[key as TranslationKey] : key }), [language])
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>
}

export function useI18n() {
  const value = useContext(I18nContext)
  if (!value) throw new Error('useI18n must be used within I18nProvider')
  return value
}

export function LanguageSwitcher() {
  const { language, setLanguage } = useI18n()
  return <div className="language-switcher" aria-label="Language"><button type="button" className={language === 'th' ? 'active' : ''} onClick={() => setLanguage('th')}>ไทย</button><button type="button" className={language === 'en' ? 'active' : ''} onClick={() => setLanguage('en')}>EN</button></div>
}
